- name: add the key for elastic repository if it's not added
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: add the debian repo for logstash
  apt_repository: repo='deb http://packages.elasticsearch.org/logstash/1.5/debian stable main' state=present

- name: install logstash
  apt: name=logstash state=present update_cache=yes

- name: copy logstash conf
  template: src=analytics.conf.j2 dest=/etc/logstash/conf.d/analytics.conf

- name: start logstash
  service: name=logstash state=started

